/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Minha API
 * Documentação oficial da API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary Criar um estabelecimento
 */
export const criarEstabelecimentoBodyNomeMin = 3;



export const CriarEstabelecimentoBody = zod.object({
  "nome": zod.string().min(criarEstabelecimentoBodyNomeMin)
})

/**
 * @summary Buscar um estabelecimento pelo ID
 */
export const BuscarUmEstabelecimentoParams = zod.object({
  "id": zod.string()
})

export const BuscarUmEstabelecimentoResponse = zod.unknown()

/**
 * @summary Editar um estabelecimento
 */
export const EditarEstabelecimentoParams = zod.object({
  "id": zod.string()
})

export const editarEstabelecimentoBodyNomeMax = 255;

export const editarEstabelecimentoBodyTelefoneMax = 20;

export const editarEstabelecimentoBodyPriceRangeMax = 20;

export const editarEstabelecimentoBodyStatusDefault = `pendente`;
export const editarEstabelecimentoBodyStatusMax = 20;

export const editarEstabelecimentoBodyVerificadoDefault = false;
export const editarEstabelecimentoBodyDestaqueDefault = false;
export const editarEstabelecimentoBodySlugMax = 255;



export const EditarEstabelecimentoBody = zod.object({
  "nome": zod.string().max(editarEstabelecimentoBodyNomeMax),
  "descricao": zod.string().optional(),
  "sobreNos": zod.string().optional(),
  "telefone": zod.string().max(editarEstabelecimentoBodyTelefoneMax).optional(),
  "priceRange": zod.string().max(editarEstabelecimentoBodyPriceRangeMax).optional(),
  "status": zod.string().max(editarEstabelecimentoBodyStatusMax).default(editarEstabelecimentoBodyStatusDefault),
  "verificado": zod.boolean().default(editarEstabelecimentoBodyVerificadoDefault),
  "destaque": zod.boolean().default(editarEstabelecimentoBodyDestaqueDefault),
  "logoUrl": zod.string().optional(),
  "coverUrl": zod.string().optional(),
  "slug": zod.string().max(editarEstabelecimentoBodySlugMax).optional()
})

export const DeleteEstabelecimentoControllerDeleteEstabelecimentoParams = zod.object({
  "id": zod.string()
})

/**
 * @summary Buscar um estabelecimento pelo ID
 */
export const BuscarUmEstabelecimentoByIdParams = zod.object({
  "id": zod.string()
})

export const buscarUmEstabelecimentoByIdResponseNomeMax = 255;

export const buscarUmEstabelecimentoByIdResponseSlugMax = 255;


export const buscarUmEstabelecimentoByIdResponseSlugRegExp = new RegExp('^[a-z0-9-]+$');
export const buscarUmEstabelecimentoByIdResponseDescricaoMax = 5000;

export const buscarUmEstabelecimentoByIdResponseTelefoneMax = 20;

export const buscarUmEstabelecimentoByIdResponseVerificadoDefault = false;
export const buscarUmEstabelecimentoByIdResponseDestaqueDefault = false;
export const buscarUmEstabelecimentoByIdResponseRatingAvgDefault = 0;
export const buscarUmEstabelecimentoByIdResponseRatingAvgMin = 0;
export const buscarUmEstabelecimentoByIdResponseRatingAvgMax = 5;

export const buscarUmEstabelecimentoByIdResponseRatingCountDefault = 0;
export const buscarUmEstabelecimentoByIdResponseRatingCountMin = 0;
export const buscarUmEstabelecimentoByIdResponseRatingCountMax = 9007199254740991;

export const buscarUmEstabelecimentoByIdResponseGooglePlaceIdMax = 255;



export const BuscarUmEstabelecimentoByIdResponse = zod.object({
  "id": zod.number().optional(),
  "nome": zod.string().min(1).max(buscarUmEstabelecimentoByIdResponseNomeMax),
  "slug": zod.string().min(1).max(buscarUmEstabelecimentoByIdResponseSlugMax).regex(buscarUmEstabelecimentoByIdResponseSlugRegExp),
  "descricao": zod.string().max(buscarUmEstabelecimentoByIdResponseDescricaoMax).nullish(),
  "sobreNos": zod.string().nullish(),
  "telefone": zod.string().max(buscarUmEstabelecimentoByIdResponseTelefoneMax).nullish(),
  "priceRange": zod.string().nullish(),
  "status": zod.string().nullish(),
  "verificado": zod.boolean().default(buscarUmEstabelecimentoByIdResponseVerificadoDefault),
  "destaque": zod.boolean().default(buscarUmEstabelecimentoByIdResponseDestaqueDefault),
  "logoUrl": zod.url().nullish(),
  "coverUrl": zod.url().nullish(),
  "ratingAvg": zod.number().min(buscarUmEstabelecimentoByIdResponseRatingAvgMin).max(buscarUmEstabelecimentoByIdResponseRatingAvgMax).default(buscarUmEstabelecimentoByIdResponseRatingAvgDefault),
  "ratingCount": zod.number().min(buscarUmEstabelecimentoByIdResponseRatingCountMin).max(buscarUmEstabelecimentoByIdResponseRatingCountMax).default(buscarUmEstabelecimentoByIdResponseRatingCountDefault),
  "googlePlaceId": zod.string().max(buscarUmEstabelecimentoByIdResponseGooglePlaceIdMax).nullish(),
  "createdAt": zod.string().nullish(),
  "updatedAt": zod.string().nullish(),
  "deletedAt": zod.string().nullish()
})

/**
 * @summary Cadastrar endereço de um estabelecimento
 */
export const CadastrarEnderecoParams = zod.object({
  "id": zod.string()
})

export const cadastrarEnderecoBodyRuaMax = 255;

export const cadastrarEnderecoBodyNumeroMax = 20;

export const cadastrarEnderecoBodyComplementoMax = 255;

export const cadastrarEnderecoBodyBairroMax = 150;

export const cadastrarEnderecoBodyCidadeMax = 150;

export const cadastrarEnderecoBodyEstadoMax = 100;

export const cadastrarEnderecoBodyCepMax = 20;





export const CadastrarEnderecoBody = zod.object({
  "rua": zod.string().min(1).max(cadastrarEnderecoBodyRuaMax),
  "numero": zod.string().min(1).max(cadastrarEnderecoBodyNumeroMax),
  "complemento": zod.string().min(1).max(cadastrarEnderecoBodyComplementoMax).nullish(),
  "bairro": zod.string().min(1).max(cadastrarEnderecoBodyBairroMax),
  "cidade": zod.string().min(1).max(cadastrarEnderecoBodyCidadeMax),
  "estado": zod.string().min(1).max(cadastrarEnderecoBodyEstadoMax),
  "cep": zod.string().min(1).max(cadastrarEnderecoBodyCepMax),
  "latitude": zod.string().min(1),
  "longitude": zod.string().min(1)
})

/**
 * @summary Buscar um endereço por estabelecimento ID
 */
export const BuscarEnderecoPorEstabelecimentoIdParams = zod.object({
  "id": zod.string()
})

export const buscarEnderecoPorEstabelecimentoIdResponseRuaMax = 255;

export const buscarEnderecoPorEstabelecimentoIdResponseNumeroMax = 20;

export const buscarEnderecoPorEstabelecimentoIdResponseComplementoMax = 255;

export const buscarEnderecoPorEstabelecimentoIdResponseBairroMax = 150;

export const buscarEnderecoPorEstabelecimentoIdResponseCidadeMax = 150;

export const buscarEnderecoPorEstabelecimentoIdResponseEstadoMax = 100;

export const buscarEnderecoPorEstabelecimentoIdResponseCepMax = 20;



export const BuscarEnderecoPorEstabelecimentoIdResponse = zod.object({
  "id": zod.number().optional(),
  "estabelecimentoId": zod.number(),
  "rua": zod.string().max(buscarEnderecoPorEstabelecimentoIdResponseRuaMax),
  "numero": zod.string().max(buscarEnderecoPorEstabelecimentoIdResponseNumeroMax),
  "complemento": zod.string().max(buscarEnderecoPorEstabelecimentoIdResponseComplementoMax),
  "bairro": zod.string().max(buscarEnderecoPorEstabelecimentoIdResponseBairroMax),
  "cidade": zod.string().max(buscarEnderecoPorEstabelecimentoIdResponseCidadeMax),
  "estado": zod.string().max(buscarEnderecoPorEstabelecimentoIdResponseEstadoMax),
  "cep": zod.string().max(buscarEnderecoPorEstabelecimentoIdResponseCepMax),
  "latitude": zod.string(),
  "longitude": zod.string()
})

/**
 * @summary Cadastrar horários de um estabelecimento
 */
export const CadastrarHorarioParams = zod.object({
  "id": zod.string()
})

export const cadastrarHorarioBodyDiaSemanaMin = -9007199254740991;
export const cadastrarHorarioBodyDiaSemanaMax = 9007199254740991;



export const cadastrarHorarioBodyIsClosedDefault = false;

export const CadastrarHorarioBodyItem = zod.object({
  "diaSemana": zod.number().min(cadastrarHorarioBodyDiaSemanaMin).max(cadastrarHorarioBodyDiaSemanaMax),
  "abre": zod.string().min(1),
  "fecha": zod.string().min(1),
  "isClosed": zod.boolean().default(cadastrarHorarioBodyIsClosedDefault)
})
export const CadastrarHorarioBody = zod.array(CadastrarHorarioBodyItem)

/**
 * @summary Buscar um horário por estabelecimento ID
 */
export const BuscarHorariosPorEstabelecimentoIdParams = zod.object({
  "id": zod.string()
})

export const buscarHorariosPorEstabelecimentoIdResponseIsClosedDefault = false;

export const BuscarHorariosPorEstabelecimentoIdResponseItem = zod.object({
  "id": zod.number().optional(),
  "estabelecimentoId": zod.number(),
  "diaSemana": zod.number(),
  "abre": zod.string(),
  "fecha": zod.string(),
  "isClosed": zod.boolean().default(buscarHorariosPorEstabelecimentoIdResponseIsClosedDefault)
})
export const BuscarHorariosPorEstabelecimentoIdResponse = zod.array(BuscarHorariosPorEstabelecimentoIdResponseItem)

/**
 * @summary Adicionar midias de um estabelecimento
 */
export const AddMidiasEstabelecimentoParams = zod.object({
  "id": zod.string()
})

export const AddMidiasEstabelecimentoBody = zod.object({
  "paths": zod.array(zod.string())
})

/**
 * @summary Buscar mídias de um estabelecimento
 */
export const BuscarMidiasEstabelecimentoParams = zod.object({
  "id": zod.string()
})

export const BuscarMidiasEstabelecimentoResponseItem = zod.string()
export const BuscarMidiasEstabelecimentoResponse = zod.array(BuscarMidiasEstabelecimentoResponseItem)

/**
 * @summary Deletar mídias de um estabelecimento
 */
export const DeletarFotosEstabelecimentoParams = zod.object({
  "id": zod.string()
})

export const DeletarFotosEstabelecimentoBody = zod.object({
  "paths": zod.array(zod.string())
})

/**
 * @summary Adicionar serviço ao estabelecimento
 */
export const AddServicoEstabelecimentoParams = zod.object({
  "id": zod.string()
})

export const addServicoEstabelecimentoBodyTituloMax = 500;



export const AddServicoEstabelecimentoBodyItem = zod.object({
  "titulo": zod.string().max(addServicoEstabelecimentoBodyTituloMax).nullish(),
  "descricao": zod.string().nullish(),
  "valor": zod.string().nullish()
})
export const AddServicoEstabelecimentoBody = zod.array(AddServicoEstabelecimentoBodyItem)

/**
 * @summary Buscar serviços por estabelecimento ID
 */
export const BuscarServicosByIdParams = zod.object({
  "id": zod.string()
})

export const BuscarServicosByIdResponseItem = zod.object({
  "id": zod.number(),
  "titulo": zod.string().nullable(),
  "descricao": zod.string().nullable(),
  "valor": zod.string().nullable(),
  "estabelecimentoId": zod.number().nullable()
})
export const BuscarServicosByIdResponse = zod.array(BuscarServicosByIdResponseItem)

/**
 * @summary Listar todas as comodidades
 */
export const ListarComodidadesResponseItem = zod.object({
  "id": zod.number(),
  "nome": zod.string(),
  "icon": zod.string().nullable(),
  "categoria": zod.string()
})
export const ListarComodidadesResponse = zod.array(ListarComodidadesResponseItem)

/**
 * @summary Listar comodidades de um estabelecimento
 */
export const ListarComodidadesPorEstabelecimentoParams = zod.object({
  "id": zod.string()
})

export const ListarComodidadesPorEstabelecimentoResponseItem = zod.object({
  "id": zod.number(),
  "nome": zod.string(),
  "icon": zod.string().nullable(),
  "categoria": zod.string()
})
export const ListarComodidadesPorEstabelecimentoResponse = zod.array(ListarComodidadesPorEstabelecimentoResponseItem)

/**
 * @summary Cadastrar comodidades do estabelecimento
 */
export const CadastrarComodidadesParams = zod.object({
  "id": zod.string()
})

export const cadastrarComodidadesBodyComodidadeIdsItemMax = 9007199254740991;




export const CadastrarComodidadesBody = zod.object({
  "comodidadeIds": zod.array(zod.number().min(1).max(cadastrarComodidadesBodyComodidadeIdsItemMax)).min(1)
})

/**
 * @summary Cadastrar redes sociais do estabelecimento
 */
export const CadastrarRedesSociaisParams = zod.object({
  "id": zod.string()
})

export const cadastrarRedesSociaisBodyTipoMax = 50;

export const cadastrarRedesSociaisBodyLabelMax = 100;



export const CadastrarRedesSociaisBodyItem = zod.object({
  "tipo": zod.string().min(1).max(cadastrarRedesSociaisBodyTipoMax),
  "url": zod.url(),
  "label": zod.string().max(cadastrarRedesSociaisBodyLabelMax).nullish()
})
export const CadastrarRedesSociaisBody = zod.array(CadastrarRedesSociaisBodyItem)

/**
 * @summary Listar redes sociais de um estabelecimento
 */
export const ListarRedesSociaisPorEstabelecimentoParams = zod.object({
  "id": zod.string()
})

export const ListarRedesSociaisPorEstabelecimentoResponseItem = zod.object({
  "id": zod.number(),
  "tipo": zod.string(),
  "url": zod.string(),
  "label": zod.string().nullable()
})
export const ListarRedesSociaisPorEstabelecimentoResponse = zod.array(ListarRedesSociaisPorEstabelecimentoResponseItem)

/**
 * @summary Adicionar avaliação ao estabelecimento
 */
export const AddAvaliacaoParams = zod.object({
  "id": zod.string()
})

export const addAvaliacaoBodyRatingMax = 5;



export const AddAvaliacaoBody = zod.object({
  "rating": zod.number().min(1).max(addAvaliacaoBodyRatingMax),
  "comentario": zod.string().nullish()
})

/**
 * @summary Listar avaliações do estabelecimento
 */
export const GetAvaliacoesParams = zod.object({
  "id": zod.string()
})

export const GetAvaliacoesResponseItem = zod.object({
  "id": zod.number(),
  "estabelecimentoId": zod.number().nullable(),
  "userId": zod.number(),
  "rating": zod.number(),
  "comentario": zod.string().nullable(),
  "approved": zod.boolean().nullable(),
  "createdAt": zod.string().nullable(),
  "updatedAt": zod.string().nullable(),
  "deletedAt": zod.string().nullable()
})
export const GetAvaliacoesResponse = zod.array(GetAvaliacoesResponseItem)

/**
 * @summary Buscar id e tipo (território ou estabelecimento) pelo host
 */
export const BuscarIdByDomainQueryParams = zod.object({
  "host": zod.string().describe('Host\/domínio (ex: loja.exemplo.com)')
})

export const BuscarIdByDomainResponse = zod.object({
  "id": zod.number(),
  "host": zod.string(),
  "tipo": zod.enum(['territorio', 'estabelecimento']),
  "territorioId": zod.number().nullable(),
  "estabelecimentoId": zod.number().nullable(),
  "ativo": zod.boolean().nullable()
})

/**
 * @summary Busca semântica de estabelecimentos
 */
export const BuscarSemanticaQueryParams = zod.object({
  "query": zod.string().describe('Texto da busca')
})

export const BuscarSemanticaResponse = zod.array()

/**
 * @summary Melhorar texto/descrição para guia comercial
 */



export const MelhorarMensagemBody = zod.object({
  "texto": zod.string().min(1)
})

export const MelhorarMensagemResponse = zod.string()

/**
 * @summary Listar estabelecimentos por território
 */
export const ListarEstabelecimentosPorTerritorioParams = zod.object({
  "territorioNome": zod.string().describe('Nome do território para filtrar os estabelecimentos')
})

export const ListarEstabelecimentosPorTerritorioResponseItem = zod.unknown()
export const ListarEstabelecimentosPorTerritorioResponse = zod.array(ListarEstabelecimentosPorTerritorioResponseItem)

