/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Minha API
 * Documentação oficial da API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary Upload de imagem
 */
export const uploadImageBodyBucketMax = 255;

export const uploadImageBodyPathMax = 255;



export const UploadImageBody = zod.object({
  "bucket": zod.string().min(1).max(uploadImageBodyBucketMax),
  "path": zod.string().min(1).max(uploadImageBodyPathMax)
})

