/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Minha API
 * Documentação oficial da API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const criarUsuarioControllerCriarUsuarioBodyEmailRegExp = new RegExp('^(?!\\.)(?!.\*\\.\\.)([A-Za-z0-9_\'+\\-\\.]\*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]\*\\.)+[A-Za-z]{2,}$');
export const criarUsuarioControllerCriarUsuarioBodyPasswordMin = 8;



export const CriarUsuarioControllerCriarUsuarioBody = zod.object({
  "name": zod.string(),
  "email": zod.email().stringFormat('email', criarUsuarioControllerCriarUsuarioBodyEmailRegExp),
  "password": zod.string().min(criarUsuarioControllerCriarUsuarioBodyPasswordMin)
})

export const BuscarUsuarioControllerBuscarUsuarioParams = zod.object({
  "email": zod.string()
})

