/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Minha API
 * Documentação oficial da API
 * OpenAPI spec version: 1.0.0
 */

export interface AddAvaliacaoDto {
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  /** @nullable */
  comentario?: string | null;
}
