/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Minha API
 * Documentação oficial da API
 * OpenAPI spec version: 1.0.0
 */

export type BuscarIdByDomainParams = {
/**
 * Host/domínio (ex: loja.exemplo.com)
 */
host: string;
};
