/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Minha API
 * Documentação oficial da API
 * OpenAPI spec version: 1.0.0
 */

export interface CadastrarEnderecoDto {
  /**
   * @minLength 1
   * @maxLength 255
   */
  rua: string;
  /**
   * @minLength 1
   * @maxLength 20
   */
  numero: string;
  /**
   * @minLength 1
   * @maxLength 255
   * @nullable
   */
  complemento?: string | null;
  /**
   * @minLength 1
   * @maxLength 150
   */
  bairro: string;
  /**
   * @minLength 1
   * @maxLength 150
   */
  cidade: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  estado: string;
  /**
   * @minLength 1
   * @maxLength 20
   */
  cep: string;
  /** @minLength 1 */
  latitude: string;
  /** @minLength 1 */
  longitude: string;
}
