/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Minha API
 * Documentação oficial da API
 * OpenAPI spec version: 1.0.0
 */

export interface CadastrarRedeSocialDto {
  /**
   * @minLength 1
   * @maxLength 50
   */
  tipo: string;
  url: string;
  /**
   * @maxLength 100
   * @nullable
   */
  label?: string | null;
}
