/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Minha API
 * Documentação oficial da API
 * OpenAPI spec version: 1.0.0
 */

export interface CadastrarHorarioDto {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  diaSemana: number;
  /** @minLength 1 */
  abre: string;
  /** @minLength 1 */
  fecha: string;
  isClosed?: boolean;
}
