/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Minha API
 * Documentação oficial da API
 * OpenAPI spec version: 1.0.0
 */
import type { EstabelecimentoDominioModelTipo } from './estabelecimentoDominioModelTipo';

export interface EstabelecimentoDominioModel {
  id: number;
  host: string;
  tipo: EstabelecimentoDominioModelTipo;
  /** @nullable */
  territorioId: number | null;
  /** @nullable */
  estabelecimentoId: number | null;
  /** @nullable */
  ativo: boolean | null;
}
