/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Minha API
 * Documentação oficial da API
 * OpenAPI spec version: 1.0.0
 */

export type EstabelecimentoDominioModelTipo = typeof EstabelecimentoDominioModelTipo[keyof typeof EstabelecimentoDominioModelTipo];


export const EstabelecimentoDominioModelTipo = {
  territorio: 'territorio',
  estabelecimento: 'estabelecimento',
} as const;
