/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Minha API
 * Documentação oficial da API
 * OpenAPI spec version: 1.0.0
 */

export interface HorarioModel {
  id?: number;
  estabelecimentoId: number;
  diaSemana: number;
  abre: string;
  fecha: string;
  isClosed?: boolean;
}
