/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Minha API
 * Documentação oficial da API
 * OpenAPI spec version: 1.0.0
 */

export interface RedeSocialModel {
  id: number;
  tipo: string;
  url: string;
  /** @nullable */
  label: string | null;
}
