/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Minha API
 * Documentação oficial da API
 * OpenAPI spec version: 1.0.0
 */

export interface UploadImageDto {
  /**
   * @minLength 1
   * @maxLength 255
   */
  bucket: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  path: string;
}
