/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Minha API
 * Documentação oficial da API
 * OpenAPI spec version: 1.0.0
 */
import type {
  UploadImageDto
} from '../../model';

import { axiosFetcher } from '../../../http/axios.http';
import type { BodyType } from '../../../http/axios.http';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * @summary Upload de imagem
 */
export const uploadImage = (
    uploadImageDto: BodyType<UploadImageDto>,
 options?: SecondParameter<typeof axiosFetcher<string>>,) => {
      return axiosFetcher<string>(
      {url: `/api/storage/upload-image`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: uploadImageDto
    },
      options);
    }
  export type UploadImageResult = NonNullable<Awaited<ReturnType<typeof uploadImage>>>
