/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Minha API
 * Documentação oficial da API
 * OpenAPI spec version: 1.0.0
 */
import type {
  AddAvaliacaoDto,
  AddMidiasEstabelecimentoDto,
  AddServicoDto,
  AvaliacaoModel,
  BuscarIdByDomainParams,
  BuscarSemanticaParams,
  CadastrarComodidadesDto,
  CadastrarEnderecoDto,
  CadastrarHorarioDto,
  CadastrarRedeSocialDto,
  ComodidadeModel,
  CriarEstabelecimentoDto,
  DeletarFotosEstabelecimentoDto,
  EditarEstabelecimentoDto,
  EnderecoModel,
  EstabelecimentoDominioModel,
  EstabelecimentoModel,
  EstabelecimentoModelOutput,
  HorarioModel,
  MelhorarMensagemDto,
  RedeSocialModel,
  ServicoModel
} from '../../model';

import { axiosFetcher } from '../../../http/axios.http';
import type { BodyType } from '../../../http/axios.http';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * @summary Criar um estabelecimento
 */
export const criarEstabelecimento = (
    criarEstabelecimentoDto: BodyType<CriarEstabelecimentoDto>,
 options?: SecondParameter<typeof axiosFetcher<number>>,) => {
      return axiosFetcher<number>(
      {url: `/api/estabelecimentos`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: criarEstabelecimentoDto
    },
      options);
    }
  /**
 * @summary Buscar um estabelecimento pelo ID
 */
export const buscarUmEstabelecimento = (
    id: string,
 options?: SecondParameter<typeof axiosFetcher<EstabelecimentoModelOutput>>,) => {
      return axiosFetcher<EstabelecimentoModelOutput>(
      {url: `/api/estabelecimentos/${id}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Editar um estabelecimento
 */
export const editarEstabelecimento = (
    id: string,
    editarEstabelecimentoDto: BodyType<EditarEstabelecimentoDto>,
 options?: SecondParameter<typeof axiosFetcher<void>>,) => {
      return axiosFetcher<void>(
      {url: `/api/estabelecimentos/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: editarEstabelecimentoDto
    },
      options);
    }
  export const deleteEstabelecimentoControllerDeleteEstabelecimento = (
    id: string,
 options?: SecondParameter<typeof axiosFetcher<void>>,) => {
      return axiosFetcher<void>(
      {url: `/api/estabelecimentos/${id}`, method: 'DELETE'
    },
      options);
    }
  /**
 * @summary Buscar um estabelecimento pelo ID
 */
export const buscarUmEstabelecimentoById = (
    id: string,
 options?: SecondParameter<typeof axiosFetcher<EstabelecimentoModel>>,) => {
      return axiosFetcher<EstabelecimentoModel>(
      {url: `/api/estabelecimentos/id/${id}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Cadastrar endereço de um estabelecimento
 */
export const cadastrarEndereco = (
    id: string,
    cadastrarEnderecoDto: BodyType<CadastrarEnderecoDto>,
 options?: SecondParameter<typeof axiosFetcher<void>>,) => {
      return axiosFetcher<void>(
      {url: `/api/estabelecimentos/${id}/enderecos`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cadastrarEnderecoDto
    },
      options);
    }
  /**
 * @summary Buscar um endereço por estabelecimento ID
 */
export const buscarEnderecoPorEstabelecimentoId = (
    id: string,
 options?: SecondParameter<typeof axiosFetcher<EnderecoModel>>,) => {
      return axiosFetcher<EnderecoModel>(
      {url: `/api/estabelecimentos/endereco/estabelecimento/${id}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Cadastrar horários de um estabelecimento
 */
export const cadastrarHorario = (
    id: string,
    cadastrarHorarioDto: CadastrarHorarioDto[],
 options?: SecondParameter<typeof axiosFetcher<void>>,) => {
      return axiosFetcher<void>(
      {url: `/api/estabelecimentos/${id}/horarios`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cadastrarHorarioDto
    },
      options);
    }
  /**
 * @summary Buscar um horário por estabelecimento ID
 */
export const buscarHorariosPorEstabelecimentoId = (
    id: string,
 options?: SecondParameter<typeof axiosFetcher<HorarioModel[]>>,) => {
      return axiosFetcher<HorarioModel[]>(
      {url: `/api/estabelecimentos/horarios/estabelecimento/${id}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Adicionar midias de um estabelecimento
 */
export const addMidiasEstabelecimento = (
    id: string,
    addMidiasEstabelecimentoDto: BodyType<AddMidiasEstabelecimentoDto>,
 options?: SecondParameter<typeof axiosFetcher<void>>,) => {
      return axiosFetcher<void>(
      {url: `/api/estabelecimentos/${id}/midias`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addMidiasEstabelecimentoDto
    },
      options);
    }
  /**
 * @summary Buscar mídias de um estabelecimento
 */
export const buscarMidiasEstabelecimento = (
    id: string,
 options?: SecondParameter<typeof axiosFetcher<string[]>>,) => {
      return axiosFetcher<string[]>(
      {url: `/api/estabelecimentos/${id}/midias`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Deletar mídias de um estabelecimento
 */
export const deletarFotosEstabelecimento = (
    id: string,
    deletarFotosEstabelecimentoDto: BodyType<DeletarFotosEstabelecimentoDto>,
 options?: SecondParameter<typeof axiosFetcher<void>>,) => {
      return axiosFetcher<void>(
      {url: `/api/estabelecimentos/${id}/midias`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deletarFotosEstabelecimentoDto
    },
      options);
    }
  /**
 * @summary Adicionar serviço ao estabelecimento
 */
export const addServicoEstabelecimento = (
    id: string,
    addServicoDto: AddServicoDto[],
 options?: SecondParameter<typeof axiosFetcher<void>>,) => {
      return axiosFetcher<void>(
      {url: `/api/estabelecimentos/${id}/servicos`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addServicoDto
    },
      options);
    }
  /**
 * @summary Buscar serviços por estabelecimento ID
 */
export const buscarServicosById = (
    id: string,
 options?: SecondParameter<typeof axiosFetcher<ServicoModel[]>>,) => {
      return axiosFetcher<ServicoModel[]>(
      {url: `/api/estabelecimentos/${id}/servicos`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Listar todas as comodidades
 */
export const listarComodidades = (
    
 options?: SecondParameter<typeof axiosFetcher<ComodidadeModel[]>>,) => {
      return axiosFetcher<ComodidadeModel[]>(
      {url: `/api/estabelecimentos/buscar/comodidades`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Listar comodidades de um estabelecimento
 */
export const listarComodidadesPorEstabelecimento = (
    id: string,
 options?: SecondParameter<typeof axiosFetcher<ComodidadeModel[]>>,) => {
      return axiosFetcher<ComodidadeModel[]>(
      {url: `/api/estabelecimentos/${id}/comodidades`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Cadastrar comodidades do estabelecimento
 */
export const cadastrarComodidades = (
    id: string,
    cadastrarComodidadesDto: BodyType<CadastrarComodidadesDto>,
 options?: SecondParameter<typeof axiosFetcher<void>>,) => {
      return axiosFetcher<void>(
      {url: `/api/estabelecimentos/${id}/comodidades`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cadastrarComodidadesDto
    },
      options);
    }
  /**
 * @summary Cadastrar redes sociais do estabelecimento
 */
export const cadastrarRedesSociais = (
    id: string,
    cadastrarRedeSocialDto: CadastrarRedeSocialDto[],
 options?: SecondParameter<typeof axiosFetcher<void>>,) => {
      return axiosFetcher<void>(
      {url: `/api/estabelecimentos/${id}/redes-sociais`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cadastrarRedeSocialDto
    },
      options);
    }
  /**
 * @summary Listar redes sociais de um estabelecimento
 */
export const listarRedesSociaisPorEstabelecimento = (
    id: string,
 options?: SecondParameter<typeof axiosFetcher<RedeSocialModel[]>>,) => {
      return axiosFetcher<RedeSocialModel[]>(
      {url: `/api/estabelecimentos/${id}/redes-sociais`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Adicionar avaliação ao estabelecimento
 */
export const addAvaliacao = (
    id: string,
    addAvaliacaoDto: BodyType<AddAvaliacaoDto>,
 options?: SecondParameter<typeof axiosFetcher<void>>,) => {
      return axiosFetcher<void>(
      {url: `/api/estabelecimentos/${id}/avaliacoes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addAvaliacaoDto
    },
      options);
    }
  /**
 * @summary Listar avaliações do estabelecimento
 */
export const getAvaliacoes = (
    id: string,
 options?: SecondParameter<typeof axiosFetcher<AvaliacaoModel[]>>,) => {
      return axiosFetcher<AvaliacaoModel[]>(
      {url: `/api/estabelecimentos/${id}/avaliacoes`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Buscar id e tipo (território ou estabelecimento) pelo host
 */
export const buscarIdByDomain = (
    params: BuscarIdByDomainParams,
 options?: SecondParameter<typeof axiosFetcher<EstabelecimentoDominioModel>>,) => {
      return axiosFetcher<EstabelecimentoDominioModel>(
      {url: `/api/estabelecimentos/dominio/buscar-id-by-domain`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Busca semântica de estabelecimentos
 */
export const buscarSemantica = (
    params: BuscarSemanticaParams,
 options?: SecondParameter<typeof axiosFetcher<unknown[]>>,) => {
      return axiosFetcher<unknown[]>(
      {url: `/api/estabelecimentos/buscar/busca-semantica`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Melhorar texto/descrição para guia comercial
 */
export const melhorarMensagem = (
    melhorarMensagemDto: BodyType<MelhorarMensagemDto>,
 options?: SecondParameter<typeof axiosFetcher<string>>,) => {
      return axiosFetcher<string>(
      {url: `/api/estabelecimentos/melhorar-mensagem`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: melhorarMensagemDto
    },
      options);
    }
  /**
 * @summary Listar estabelecimentos por território
 */
export const listarEstabelecimentosPorTerritorio = (
    territorioNome: string,
 options?: SecondParameter<typeof axiosFetcher<EstabelecimentoModelOutput[]>>,) => {
      return axiosFetcher<EstabelecimentoModelOutput[]>(
      {url: `/api/estabelecimentos/territorio/${territorioNome}`, method: 'GET'
    },
      options);
    }
  export type CriarEstabelecimentoResult = NonNullable<Awaited<ReturnType<typeof criarEstabelecimento>>>
export type BuscarUmEstabelecimentoResult = NonNullable<Awaited<ReturnType<typeof buscarUmEstabelecimento>>>
export type EditarEstabelecimentoResult = NonNullable<Awaited<ReturnType<typeof editarEstabelecimento>>>
export type DeleteEstabelecimentoControllerDeleteEstabelecimentoResult = NonNullable<Awaited<ReturnType<typeof deleteEstabelecimentoControllerDeleteEstabelecimento>>>
export type BuscarUmEstabelecimentoByIdResult = NonNullable<Awaited<ReturnType<typeof buscarUmEstabelecimentoById>>>
export type CadastrarEnderecoResult = NonNullable<Awaited<ReturnType<typeof cadastrarEndereco>>>
export type BuscarEnderecoPorEstabelecimentoIdResult = NonNullable<Awaited<ReturnType<typeof buscarEnderecoPorEstabelecimentoId>>>
export type CadastrarHorarioResult = NonNullable<Awaited<ReturnType<typeof cadastrarHorario>>>
export type BuscarHorariosPorEstabelecimentoIdResult = NonNullable<Awaited<ReturnType<typeof buscarHorariosPorEstabelecimentoId>>>
export type AddMidiasEstabelecimentoResult = NonNullable<Awaited<ReturnType<typeof addMidiasEstabelecimento>>>
export type BuscarMidiasEstabelecimentoResult = NonNullable<Awaited<ReturnType<typeof buscarMidiasEstabelecimento>>>
export type DeletarFotosEstabelecimentoResult = NonNullable<Awaited<ReturnType<typeof deletarFotosEstabelecimento>>>
export type AddServicoEstabelecimentoResult = NonNullable<Awaited<ReturnType<typeof addServicoEstabelecimento>>>
export type BuscarServicosByIdResult = NonNullable<Awaited<ReturnType<typeof buscarServicosById>>>
export type ListarComodidadesResult = NonNullable<Awaited<ReturnType<typeof listarComodidades>>>
export type ListarComodidadesPorEstabelecimentoResult = NonNullable<Awaited<ReturnType<typeof listarComodidadesPorEstabelecimento>>>
export type CadastrarComodidadesResult = NonNullable<Awaited<ReturnType<typeof cadastrarComodidades>>>
export type CadastrarRedesSociaisResult = NonNullable<Awaited<ReturnType<typeof cadastrarRedesSociais>>>
export type ListarRedesSociaisPorEstabelecimentoResult = NonNullable<Awaited<ReturnType<typeof listarRedesSociaisPorEstabelecimento>>>
export type AddAvaliacaoResult = NonNullable<Awaited<ReturnType<typeof addAvaliacao>>>
export type GetAvaliacoesResult = NonNullable<Awaited<ReturnType<typeof getAvaliacoes>>>
export type BuscarIdByDomainResult = NonNullable<Awaited<ReturnType<typeof buscarIdByDomain>>>
export type BuscarSemanticaResult = NonNullable<Awaited<ReturnType<typeof buscarSemantica>>>
export type MelhorarMensagemResult = NonNullable<Awaited<ReturnType<typeof melhorarMensagem>>>
export type ListarEstabelecimentosPorTerritorioResult = NonNullable<Awaited<ReturnType<typeof listarEstabelecimentosPorTerritorio>>>
