/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Minha API
 * Documentação oficial da API
 * OpenAPI spec version: 1.0.0
 */
import type {
  CriarUsuarioDto
} from '../../model';

import { axiosFetcher } from '../../../http/axios.http';
import type { BodyType } from '../../../http/axios.http';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const criarUsuarioControllerCriarUsuario = (
    criarUsuarioDto: BodyType<CriarUsuarioDto>,
 options?: SecondParameter<typeof axiosFetcher<void>>,) => {
      return axiosFetcher<void>(
      {url: `/api/usuarios`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: criarUsuarioDto
    },
      options);
    }
  export const buscarUsuarioControllerBuscarUsuario = (
    email: string,
 options?: SecondParameter<typeof axiosFetcher<void>>,) => {
      return axiosFetcher<void>(
      {url: `/api/usuarios/find/${email}`, method: 'GET'
    },
      options);
    }
  export const minhasInformacoesControllerGetProfile = (
    
 options?: SecondParameter<typeof axiosFetcher<void>>,) => {
      return axiosFetcher<void>(
      {url: `/api/usuarios/me`, method: 'GET'
    },
      options);
    }
  export type CriarUsuarioControllerCriarUsuarioResult = NonNullable<Awaited<ReturnType<typeof criarUsuarioControllerCriarUsuario>>>
export type BuscarUsuarioControllerBuscarUsuarioResult = NonNullable<Awaited<ReturnType<typeof buscarUsuarioControllerBuscarUsuario>>>
export type MinhasInformacoesControllerGetProfileResult = NonNullable<Awaited<ReturnType<typeof minhasInformacoesControllerGetProfile>>>
